Adding nucleo_f401re
AdaCore/bb-runtimes pull request #46
Opened 2020-12-08 21:48 UTC by FredPraca

Here we go once again :smile:

2020-12-10 09:18 UTC, Fabien-Chouteau requested changes

2020-12-10 09:18 UTC, Fabien-Chouteau commented on arm/stm32/stm32f401/memory-map.ld
> + *                   Copyright (C) 2003-2015 AdaCore                        *
This should be `2003-2020`

2020-12-10 09:18 UTC, Fabien-Chouteau commented on arm/stm32/stm32f401/s-bbmcpa.adb
> +--                      Copyright (C) 2016, AdaCore                         --
This should be `2020`

2020-12-10 09:18 UTC, Fabien-Chouteau commented on arm/stm32/stm32f401/s-bbmcpa.ads
> +--                      Copyright (C) 2016, AdaCore                         --
This should be `2020`

2020-12-10 09:18 UTC, Fabien-Chouteau commented on arm/stm32/stm32f401/s-stm32.adb
> +--          Copyright (C) 2012-2016, Free Software Foundation, Inc.         --
This should be `2012-2020`

2020-12-10 20:31 UTC, FredPraca commented on arm/stm32/stm32f401/memory-map.ld
> + *                   Copyright (C) 2003-2015 AdaCore                        *
Done

2020-12-14 16:54 UTC, Fabien-Chouteau commented
Thank you @FredPraca  we will review the code and get back to you as soon as possible.

2021-01-07 15:04 UTC, merged

2021-01-07 15:04 UTC, Fabien-Chouteau commented
The PR is merged, thank you @FredPraca !