Add support for Raspberry Pi Pico (RP2040)
AdaCore/bb-runtimes pull request #51
Opened 2021-03-09 22:04 UTC by damaki

This adds support for the dual-core RP2040 microcontroller and the Raspberry Pi Pico board.

Support is added for Ravenscar-full and Ravenscar-sfp runtimes only. Projects on the Pico that require a ZFP runtime can use the the generic `zfp-cortex-m0p` runtime, with startup code available in the `pico_bsp` crate in Alire.

Two runtime variants are supported for the Pico:
* `rpi-pico-sp` is a single processor variant where Ada tasks and interrupts are dispatched on core0 only. core1 can be used for other purposes, for example [pico-debug](https://github.com/majbthrd/pico-debug/).
* `rpi-pico-mp` is the multiprocessor variant where Ada tasks and interrupts can be dispatched on either core. The `CPU` attribute can be used to assign tasks to either core, allowing tasks to be executed in parallel. For example:

```Ada
task Run_On_First_Core  with CPU => 1;
task Run_On_Second_Core with CPU => 2;
```

Further details are documented in `arm/rpi/rp2040/README`

2021-03-10 15:11 UTC, Fabien-Chouteau requested changes
Hello @damaki, thanks for the contribution.
This is a nice achievement.

One general comment about this pull request is that there is a lot of code copy pasted from various sources (like Pico SDK) with different copyright holders and I am not comfortable merging all this in our repo.

2021-03-10 15:11 UTC, Fabien-Chouteau commented on arm/cortexm.py
> +class RpiPicoSP(RP2040SP):
There is a lot of duplication here, MP and SP classes should be merged.
You can have a look here for instance: https://github.com/AdaCore/bb-runtimes/blob/8f08b89e4bd3ca79c7ce616f74d462921ce70534/sparc/__init__.py#L156

2021-03-10 17:20 UTC, damaki commented on src/s-bcpcst__rp2040.adb
> +package body System.BB.CPU_Primitives.Context_Switch_Trigger is
Unfortunately the existing implementation in `s-bcpcst__pendsv.adb` does not work correctly on multiprocessor systems. 

The PendSV context switching implementation makes two table lookups: `__gnat_running_thread_table` and `first_thread_table`, but always accesses the first element of the array. This works fine on core0, but on core1 the context switch must access the second element in the table, otherwise it will context switch to the wrong task.

The RP2040 version of this package has some extra instructions to read the RP2040's CPUID register (to determine which core it is running on) then calculate the correct table offset.

I considered updating `s-bcpcst__pendsv.adb` to call `Current_CPU` and calculate the correct offset, but felt that that this would add useless overhead to performance-critical code for all other (single-core) ARM runtimes. I therefore decided to adapt it to a separate version that can be selected only when it is absoutely necessary, i.e. when building the the `rpi-pico-mp` runtime.

2021-03-10 17:20 UTC, damaki commented on src/s-bbsumu__rp2040.adb
> +         --  Write to the TX FIFO (mailbox) to generate an interrupt on core1
None that I'm aware of.

Each core has its own NVIC, but it cannot be accessed directly by the other core. The cores can send events to each other via the `sev` instruction, but this does not generate an interrupt.

The FIFO is intended for inter-core communication, and fits this purpose nicely. Although this reserves the FIFO for use by the runtime, user applications should not need to use the FIFO since Ada's protected objects provide a much nicer mechanism for inter-task communication across cores.

2021-03-10 17:20 UTC, damaki commented on src/s-bbbosu__rp2040.adb
> +         if Interrupt > IRQ_ID'Last then
The interrupt handlers are installed during elaboration, which runs on core0 only (before core1 is started). Unfortunately, core0 does not have direct access to core1's NVIC, so it cannot directly configure the `IP` and `ISER` registers. Instead, core0 caches the NVIC configuration for core1 in RAM, which is used later when core1 is started.

I will update the comments to explain this better.

2021-03-10 17:20 UTC, damaki commented on arm/rpi/rp2040/a-intnam__mp.ads
> +   TIMER_IRQ_0_Interrupt_CPU_2    : constant Interrupt_ID := 32 + 0;
Thanks!

2021-03-10 17:20 UTC, damaki commented on arm/rpi/rp2040/handler__mp.S
> +	.word   __gnat_poke_handler  /* IRQ15 */
The only other difference is in the SysTick handler:
* on `rpi-pico-sp` the SysTick is used by the runtime so the IRQ handler is `__gnat_sys_tick_trap`.
* on `rpi-pico-mp` the SysTick is **not** used by the runtime (TIMER Alarm 3 is used instead) so the IRQ handler is `isr_systick` so that it can be used/implemented by the user application (if needed).

I'm open to suggestions if you have a better idea to handle this so that we can have a single `handler.S`.

2021-03-10 17:20 UTC, damaki commented on arm/cortexm.py
> +class RpiPicoSP(RP2040SP):
Thanks for the tip! I'll refactor these classes to remove the duplication.

2021-03-10 17:35 UTC, damaki commented
> One general comment about this pull request is that there is a lot of code copy pasted from various sources (like Pico SDK) with different copyright holders and I am not comfortable merging all this in our repo.

I understand your concern. The files that were adapted from the Pico SDK are:
* `arm/rpi/rp2040/boot2__w25q080.S`
* `arm/rpi/rp2040/crt0.S.tmpl`
* `arm/rpi/rp2040/memmap_copy_to_ram.ld`
* `arm/rpi/rp2040/memmap_default.ld`
* `arm/rpi/rp2040/memmap_no_flash.ld`

The SVD files were generated from `rp2040.svd` that was contributed to the svd2ada project. 

All other files in this contribution were written from scratch (e.g. `s-bootro.adb`), or were adapted from existing sources in bb-runtimes.

I could delete the code that was copied from the Pico SDK and replaced it with code that was adapted from other sources in bb-runtimes. For example, delete `crt0.S.tmpl` and replace it with an implementation adapted from `arm/stm32/stm32f0xx/start-rom.S`, and similarly for the memory maps.

The only remainining file would be `boot2__w25q080.S` which was pre-compiled from Pico SDK. I can look into replacing this with a pure Ada implementation.

Would that be acceptable to you?

2021-05-25 20:48 UTC, damaki commented on src/s-bbpara__cortexm0p.ads
> +package System.BB.Parameters is
I've made this package into a template in db35c4c

2021-05-25 20:49 UTC, damaki commented on src/s-bbbosu__rp2040.adb
> +         if Interrupt > IRQ_ID'Last then
I've made a couple of changes to improve this:
* Improved the explanation in the comments; and
* Made better use of types to distinguish between IRQ lines on each core and the logical interrupt IDs, with appropriate functions to clearly convert between the two.

2021-05-25 20:52 UTC, damaki commented on arm/rpi/rp2040/handler__mp.S
> +	.word   __gnat_poke_handler  /* IRQ15 */
I've removed the duplication of the vector tables in db35c4c by making these IRQ handlers a template config value. 

I did consider your suggestion of checking the interrupt ID and calling the poke handler, but it is not straightforward to make it work with both SP and MP runtimes, since the poke handler is only defined when building the MP runtime. So instead I went with a template approach.

2021-05-25 20:52 UTC, damaki commented on arm/cortexm.py
> +class RpiPicoSP(RP2040SP):
I've removed the duplication in db35c4c

2021-05-25 21:02 UTC, damaki commented
> One general comment about this pull request is that there is a lot of code copy pasted from various sources (like Pico SDK) with different copyright holders and I am not comfortable merging all this in our repo.

In commit db35c4c I've removed the startup code and linker scripts that were copied from the Pico SDK (i.e. the `crt0.S.tmpl` and `memmap_*.ld` files) and have replaced them with files that were adapted from existing sources in bb-runtimes (from the STM32 runtimes).

The only thing that still remains from Pico SDK is the precompiled bootloader (`boot2__w25q080.S`). I did some experiments trying to write a pure Ada implementation, but ran into several problems that made it quite difficult. Would you be happy to keep this file, or does it also need to be replaced?

2021-05-25 23:19 UTC, JeremyGrosser commented
It's worth noting that all of the code that was copied from pico-sdk is BSD-3-Clause licensed and I've made rp2040_hal, pico_bsp, and pico_examples available under the same. The boot2 code is generated by preprocessing the BSD licensed code with Debian's FSF GCC toolchain which does not impose any additional license requirements on generated artifacts.

2021-05-28 10:09 UTC, Fabien-Chouteau commented on arm/cortexm.py
> +def make_rpipico(target_name, base_rp2040):
Same here, you should not have to do this.

2021-05-28 10:18 UTC, Fabien-Chouteau commented
> The boot2 code is generated by preprocessing the BSD licensed code with Debian's FSF GCC toolchain which does not impose any additional license requirements on generated artifacts.

It is not so much about the license, but the Contributor License Agreement.

2021-05-28 11:14 UTC, damaki commented on arm/cortexm.py
> +class RP2040SP(CortexM0P):
Aha, I see how it's done there now. I'll use the same approach of an `smp` parameter for the RP2040 and RpiPico classes. Thanks for the tip.

2021-05-28 11:14 UTC, damaki commented on arm/cortexm.py
> +def make_rpipico(target_name, base_rp2040):
Yep, thanks, I'll undo this and turn it into a single class.

2021-05-28 11:23 UTC, damaki commented
> What was the problem?

The main challenges I came across was a) fitting it all in 252 bytes, and b) lack of initialsation on entry to the bootloader. Mainly it was getting it all to fit into 252 bytes, though, given that I needed more initialisation in the pure Ada code (e.g. needed a stack pointer).

> Ideally having a source version would be best.

> It is not so much about the license, but the Contributor License Agreement.

Thanks for clarifying. I'll continue working on a clean implementation of the bootloader, along with associated scripts to generate the CRC etc during runtime generation.

2021-05-28 12:01 UTC, damaki commented on arm/cortexm.py
> +class RP2040SP(CortexM0P):
I've merged these two classes into a single one in 46ec61c.

I've also changed the pico runtime names to be consistent with the existing naming scheme in the Leon3 targets. The names are now:
* rpi-pico
* rpi-pico-smp

2021-09-19 20:48 UTC, damaki commented
Closing this PR as this work has since been updated & rebased to the `community-2021` branch. See #55.

2021-09-19 20:48 UTC, closed without merging