Added NRF52833 (MicrobitV2) Ravenscar and Jorvik support
AdaCore/bb-runtimes pull request #63
Opened 2022-12-11 15:41 UTC by aiunderstand

**To build run:**
python .\build_rts.py --output=C:\GNAT\2021-arm-elf\arm-eabi\lib\gnat --build nrf52833 --force

**Requirements:**
- ARM-ELF installation
- Windows users: update path system variable in "environment variables" to include:
 "C:\GNAT\2021-arm-elf\bin"
 "C:\Users\<username>\AppData\Local\Program\Python\Python39\"
 "C:\Users\<username>\AppData\Local\Program\Python\Python39\Scripts\"

**Notes:** 
Tested runtimes: 
- ravenscar-full-nrf52833 (jorvik)
- ravenscar-sfp-nrf52833 (ravenscar)

_NOT working_ (see some relevant discussion in ADL PR for MicrobitV2)
- zfp-nrf52833
For ZFP use the ZFP-Cortex-M4 runtime with custom MicrobitV2 linker file and crt0.S

2022-12-11 15:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AdaCore/bb-runtimes?pullRequest=63) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AdaCore/bb-runtimes?pullRequest=63) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AdaCore/bb-runtimes?pullRequest=63) it.</sub>

2022-12-12 17:33 UTC, Fabien-Chouteau commented on src/s-textio__microbit_v2.adb
> +package body System.Text_IO is
For ARM Cortex-M board we always use semihosting for Text IO, so you don't have to implement this package.

Add this to your `NRF52833` class in `cortexm.py`:
```python
    @property
    def use_semihosting_io(self):
        return True
```

2022-12-13 10:33 UTC, aiunderstand commented on src/s-textio__microbit_v2.adb
> +package body System.Text_IO is
I have enabled default semihosting and removed the reference to the microbit_v2 semihosting one in cortexm.py. In addition done several small syntax fixes to enable linux build.

2023-09-22 10:45 UTC, jklmnn requested changes
All in all it looks good. I commented on a few small style issues.

2023-09-22 10:45 UTC, jklmnn commented on arm/nordic/nrf52/nrf52833/svd/a-intnam.ads
> +--  This spec has been automatically generated from nrf52.svd and than modified
I think it should be "then" instead of "than".

2023-09-22 10:45 UTC, jklmnn commented on arm/nordic/nrf52/nrf52833/svd/a-intnam.ads
> +--  https://infocenter.nordicsemi.com/pdf/nRF52833_PS_v1.3.pdf page 22/23
As this is a multi line comment it needs to end with a `.`.

2023-09-22 10:45 UTC, jklmnn commented on arm/nordic/nrf52/nrf52833/svd/a-intnam.ads
> +--  ARM 32-bit Cortex-M4 Microcontroller  MCU
There is a double space before MCU. And it also needs to end with a `.`.

2023-09-22 10:45 UTC, jklmnn commented on arm/nordic/nrf52/nrf52840/svd/a-intnam.ads
> -end Ada.Interrupts.Names;
Can you please remove this unrelated change.

2023-09-22 10:45 UTC, jklmnn commented on arm/nordic/nrf52/s-bbmcpa.ads
> ---  This package defines MCU parameters for the nRF52840
This file is used for all nRF52 targets. Can you please change the comment to e.g. "for the nRF52 family"?

2023-09-22 10:45 UTC, jklmnn commented on arm/nordic/nrf52/system-xi-nrf52-full.ads
>  --  This is a Ravenscar run time
Please also change the comment to Jorvik.

2023-09-22 10:45 UTC, jklmnn commented on sparc/__init__.py
> +            del (ret['zfp'])
Please remove this unrelated change.

2023-09-22 10:45 UTC, jklmnn commented on support/bsp_sources/installer.py
> -
Please remove this unrelated change.

2023-09-22 10:45 UTC, jklmnn commented on support/files_holder.py
> -    return(re.sub(r'\"\$\{([^\$\"\}]*)\}\"', lookup, content))
Please remove this unrelated change.

2023-09-22 10:45 UTC, jklmnn commented on support/rts_sources/__init__.py
> -            del(env[next_var])
Please remove these unrelated changes.

2023-09-22 10:45 UTC, jklmnn commented on src/s-textio__microbit_v2.adb
> +package body System.Text_IO is
IIUC correctly this file isn't needed anymore. Can you please remove it?

2023-09-23 15:09 UTC, aiunderstand commented on src/s-textio__microbit_v2.adb
> +package body System.Text_IO is
Done! Thanks for the feedback @Fabien-Chouteau  and @jklmnn

2023-09-23 15:10 UTC, aiunderstand commented
> All in all it looks good. I commented on a few small style issues.

Thanks for the detailed feedback @jklmnn . All suggested changes are committed.

2023-09-23 15:18 UTC, aiunderstand commented
Sorry, I deleted the files with unrelated changes instead of removing my style changes. I will add them back

2023-09-23 16:31 UTC, aiunderstand commented
This PR, which enables ravenscar and jorvik support for the NRF52833 (eg. Micro:Bit v2) has now integrated the style suggestions, re-enabled semi-hosting and removed the s-textio file. 

It builds the nrf52833 runtimes using the command stated above resulting in: 

![image](https://github.com/AdaCore/bb-runtimes/assets/6376127/5bdb2c3c-c652-4a5c-961f-57ec42295ed6)
 
Note that the runtimes are created using the 2021 toolchain

2023-09-25 12:44 UTC, jklmnn commented
> Note that the runtimes are created using the 2021 toolchain

Do you specifically need these changes for the 2021 toolchain? Otherwise I would merge these changes into master so they will be available in upcoming releases.

2023-09-26 11:33 UTC, jklmnn commented
This repository is mirrored from our internal one. Unfortunately the master branch in this repository is not up to date at the moment but I'm already working on that. I will put your changes through our internal review (I don't expect any major changes there) and if you're okay with it I would take care of rebasing your changes to the latest master and merge them. Your commits should then pop up here.

2023-09-26 11:41 UTC, aiunderstand commented
Thanks, I look forward to your commit.

2023-09-26 13:34 UTC, jklmnn commented
I just noticed you were using merge commits within the git history of this PR. We can only merge changes that apply cleanly to our master branch. Are you okay with me cleaning up the git history of your changes (remove the merge commits, squash style fixes)? Your name and email address will of course stay in these commits.

2023-09-26 17:20 UTC, aiunderstand commented
Ofcourse! Apologies for the extra work.

On Tue, Sep 26, 2023, 15:35 JK ***@***.***> wrote:

> I just noticed you were using merge commits within the git history of this
> PR. We can only merge changes that apply cleanly to our master branch. Are
> you okay with me cleaning up the git history of your changes (remove the
> merge commits, squash style fixes)? Your name and email address will of
> course stay in these commits.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AdaCore/bb-runtimes/pull/63#issuecomment-1735556690>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABQUVP2QU6RM75IPRW2BQ3TX4LKYJANCNFSM6AAAAAAS3BR7WI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-26 22:27 UTC, aiunderstand commented
I created a new branch nrf52833 on my repo forked from the latest upstream/community-2021 branch. I then added all files, checked that it worked and submitted a PR.

2023-10-03 15:13 UTC, aiunderstand commented
Hi @jklmnn is there something I need to do for this PR to be integrated?

2023-10-05 11:22 UTC, aiunderstand commented
Of course! Thanks

> > Hi @jklmnn is there something I need to do for this PR to be integrated?
> 
> Unfortunately I'm quite busy these days, I'll try to look as soon as possible at #67. Are you fine with closing this one so we don't have duplicates?

Of course!

2023-10-06 11:30 UTC, jklmnn commented
Closed in favor of #67.

2023-10-06 11:30 UTC, closed without merging