Added NRF52833 (Micro:Bit v2) Ravenscar and Jorvik profiles
AdaCore/bb-runtimes pull request #67
Opened 2023-09-26 22:23 UTC by aiunderstand

2023-10-06 14:47 UTC, jklmnn requested changes
Except of two little things it looks good. You can simply amend your commit by using `git commit --amend` and then force push to this branch to keep it as a single commit.

2023-10-06 14:47 UTC, jklmnn commented on arm/nordic/nrf52/nrf52833/s-bbbopa.ads
> +--  This package defines board parameters for the nRF52840-DK board
This should be `nRF52833` instead of `nRF52840-DK`.

2023-10-06 14:47 UTC, jklmnn commented on arm/nordic/nrf52/system-xi-nrf52-full.ads
> +--  This is a Jorvik (formerly known as GNAT_Extended_Ravenscar) run time
Can you please change the comment to "This is a bare metal tasking runtime". We have recently changed our runtimes to Jorvik and discussed what comment to put here internally.

2023-10-08 22:12 UTC, aiunderstand commented on arm/nordic/nrf52/system-xi-nrf52-full.ads
> +--  This is a Jorvik (formerly known as GNAT_Extended_Ravenscar) run time
Done!

2023-10-08 22:13 UTC, aiunderstand commented
Done!

2023-10-09 10:22 UTC, jklmnn approved these changes

2023-10-09 10:24 UTC, jklmnn commented
Thanks! I'll update the internal review and let you know once it has been merged.

2024-04-08 10:48 UTC, closed without merging